FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY apps/api/package*.json ./
RUN npm install

# Copy source
COPY apps/api/ ./

# Generate Prisma client
RUN npx prisma generate

EXPOSE 5000
EXPOSE 8080

CMD ["npm", "run", "dev"]